server {

	# IPv4 adresses
	listen 443 ssl;
	# IPv6 adresses
	listen [::]:443 ssl; 
	ssl_protocols TLSv1.3;
	ssl_certificate /etc/nginx/cert/inception.crt;	# TSL Certificate
	ssl_certificate_key /etc/nginx/tsl_key/inception.key;	# Clef

	# Configuration du serveur Wordpress (root, index et server_name)
	root /var/www/html;
	# Localhost only stays here for purpose demo
	server_name localhost flverge.42.fr www.flverge.42.fr;
	# Look for the index.php
	index index.php;

	# Configuration for handling PHP files
	location ~ [^/]\\.php(/|$) {
		# Try to serve the file, if not found return 404
		try_files $uri =404;
		# Pass the request to the FastCGI server running on wordpress:9000
		fastcgi_pass wordpress:9000;
		# Include the default FastCGI parameters
		include fastcgi_params;
		# Set the SCRIPT_FILENAME parameter to the path of the script
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}