# Docker compose is a tool to manage multi-containers app, run and stop them with one command

# global env file do not works
# env_file:
#   -path: ./.env

services:
  nginx:
    build: nginx/
    ports:
      - "8080:80"
    env_file:
      - ./.env
    restart: always
