# Docker compose is a tool to manage multi-containers app, run and stop them with one command
services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile # If dockerfile is not named Dockerfile
      # Build time arguments
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    ports:
      - "443:443"
    # Run time env variables plugged as variables envs
    env_file:
      - ./.env
    volumes:
      - wordpress_volume:/var/www/wordpress
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      # Build time arguments
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    # Run time env variables plugged as variables envs
    env_file:
      - ./.env
    expose:
      - "3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: on-failure # ! regarder les differentes options

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      # Build time arguments
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        SCRIPTS_FOLDER: ${SCRIPTS_FOLDER}
    # Run time env variables plugged as variables envs
    env_file:
      - ./.env
    expose:
      - "9000"
    volumes:
      - wordpress_volume:/var/www/wordpress
    restart: on-failure

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mysql
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    name: inception