# Docker compose is a tool to manage multi-containers app, run and stop them with one command

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      # Build time arguments
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        PATH_NGINX_CERTIFICATE: ${PATH_NGINX_CERTIFICATE}
        PATH_NGINX_TSL_KEY: ${PATH_NGINX_TSL_KEY}
    ports:
      - "443:443"
    # Run time env variables plugged as variables envs
    env_file:
      - ./.env
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      # Build time arguments
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    # Run time env variables plugged as variables envs
    env_file:
      - ./.env
    restart: always