# Docker compose is a tool to manage multi-containers app, run and stop them with one command

# global env file do not works
# env_file:
#   -path: ./.env

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args: # Use all the .env variables
        ALPINE_VERSION : ${ALPINE_VERSION}
        PATH_NGINX_CERTIFICATE : ${PATH_NGINX_CERTIFICATE}
        PATH_NGINX_TSL_KEY : ${PATH_NGINX_TSL_KEY}
        URL : ${URL}
        LOGIN : ${LOGIN}
    ports:
      - "8080:80"
    env_file:
      - ./.env
    restart: always
