# Docker compose is a tool to manage multi-containers app, run and stop them with one command

################################################################################
############################# MANDATORY   SERVICES #############################
################################################################################
services:
  mariadb:
    container_name: mariadb
    build:
      # Target the Dockerfile location
      context: ./requirements/mariadb
      # Over specify `dockerfile:` only necessary if the Dockerfile is not named `Dockerfile`
      dockerfile: Dockerfile
      args:
        # Build time arguments, which allows to leverage env variables because....
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    # .... ENV Variables are not available during the building process, only when container starts
    image: mariadb
    env_file:
      - .env
    # Expose = Expose a port within a Docker Networks. The port is then not available for the host.
    expose:
      - 3306
    # Define which part of the container is a bind mount (see note lower)
    volumes:
      - mariadb_volume:/var/lib/mysql
    # Healthcheck : A health check is a shell command which runs continuously within the container.
    # The healthcheck is usefull for tagging a container "Healthy", which is mostly used for
    # synchronizing containers starting order with the `depends-on` instruction.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s # Run the healthcheck every 5 seconds
      timeout: 5s # If the command does not success in this timeframe, healthcheck fails
      retries: 10 # Number of consecutive failures before marking the container as unhealthy 
    # Should run continuously but can be stopped manually
    restart: unless-stopped
    # Attach the container in a Docker network, which makes container within the same network to "talk" to each other.
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    # depends-on does tell compose on which order to start the containers.
    depends_on:
      mariadb:
        condition: service_healthy
      redis_commander:
        condition: service_started
    build:
      context: ./requirements/wordpress
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: wordpress
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress_volume:/var/www/html
    restart: on-failure
    healthcheck:
      test: ["CMD", "sh", "-c", "[ -d /run/php ]"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - inception_network

  nginx:
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        PATH_NGINX_CERTIFICATE: ${PATH_NGINX_CERTIFICATE}
        PATH_NGINX_TSL_KEY: ${PATH_NGINX_TSL_KEY}
    # Port : make a port available to the host.
    image: nginx
    ports:
      - 443:443
      # - 4242:4242
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
      - static_website_volume:/var/www/static_website
    networks:
      - inception_network

################################################################################
################################ BONUS SERVICES ################################
################################################################################
  redis:
    # hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 1s
      retries: 10
    container_name: redis
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./requirements/bonus/1_redis
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: redis
    env_file:
    - .env
    # expose:
    # - 6379
    ports:
    - 6379:6379
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    networks:
      - inception_network

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/2_ftp
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        # FTP_USER: ${FTP_USER}
        # FTP_PASSWORD: ${FTP_PASSWORD}
    image: ftp
    env_file:
      - .env
    ports:
      - 20:20 #FTP DATA PORT
      - 21:21 #FTP DATA PORT
      - "40000-40005:40000-40005"
    volumes:
      - wordpress_volume:/home/flverge/ftp/files
    restart: always
    networks:
      - inception_network

  static_website:
    container_name: static_website
    build:
      context: ./requirements/bonus/3_static_website
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: static_website
    env_file:
      - .env
    # expose: #really usefull ?
    #   - 4242
    volumes:
      - static_website_volume:/var/www/static_website
    restart: always
    networks:
      - inception_network

  adminer:
    container_name: adminer
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./requirements/bonus/4_adminer
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: adminer
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - mariadb_volume:/var/lib/mysql # data location (see config file)
    restart: always
    networks:
      - inception_network

  redis_commander:
    container_name: redis_commander
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: ./requirements/bonus/5_redis_commander
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: redis_commander
    env_file:
      - .env
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=test:redis:6379
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    networks:
      - inception_network


################################################################################
################################ DOCKER VOLUMES ################################
################################################################################

#                   !  NOTE ON BIND MOUNT
# A bind mount allows you to mount a directory or file from the host machine
# into the container. This is useful for sharing data between the host and the container.


volumes:
  # Define a volume identified as 'mariadb_volume' only within the docker-compose
  mariadb_volume:
    # Use the local driver for the volume
    driver: local
    # Define a name of the volume which serves as identifier for containers
    name: mariadb_volume
    driver_opts:
      # Specify the type as 'none' to use a bind mount
      type: none
      # When assigned to a container, the mariadb_volume will reflect what's in this specified path.
      device: '/home/${USER}/data/mariadb'
      # Bind the specified host path to the volume
      o: bind

  wordpress_volume:
    driver: local
    name: wordpress_volume
    driver_opts:
      type: none
      device: '/home/${USER}/data/wordpress'  
      o: bind
  
  static_website_volume:
    driver: local
    name: static_website_volume
    driver_opts:
      type: none
      device: '/home/${USER}/data/static_website_volume'  
      o: bind

################################################################################
################################ DOCKER NETWORK ################################
################################################################################
networks:
  inception_network:
    name: inception_network