# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: flverge <flverge@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/23 16:58:21 by flverge           #+#    #+#              #
#    Updated: 2024/12/29 16:30:05 by flverge          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

ARG DEBIAN_VERSION
FROM debian:${DEBIAN_VERSION:-bullseye}

RUN apt-get update && apt-get install -y vsftpd

COPY conf/vsftpd.conf /tmp/vsftpd.conf

COPY conf/launchFTP.sh /

RUN chmod +x launchFTP.sh

ENTRYPOINT ["bash", "launchFTP.sh"]
