listen=YES

# Allow local users to log in
local_enable=YES

# Enable file uploads
write_enable=YES

# Restrict users to their home directories
chroot_local_user=YES

# Limit access to specific users (optional)
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

allow_writeable_chroot=YES

local_root=/var/www/html

anonymous_enable=NO